services:
  web:
    build: .
    image: ${FULL_IMAGE_NAME}
    container_name: motasu-web-${DEPLOY_ENV}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${HOST_PORT}:80"
    volumes:
      - ./config/config.json:/usr/share/nginx/html/assets/config.json:ro