services:
  web:
    build: .
    image: ${FULL_IMAGE_NAME}
    container_name: motasu-web-${DEPLOY_ENV}
    restart: unless-stopped
    ports:
      # On bind uniquement en local.
      # Le conteneur écoute sur 80, on le mappe sur HOST_PORT sur la VM
      - "127.0.0.1:${HOST_PORT}:80"